// Auditable Bash source, shared by the static page and its script tests.
(function (root) {
  const template = `#!/usr/bin/env bash
# Generated by Shelf, a static website. Review this file before running it.
# This script runs yt-dlp locally and contacts Instagram and its media services.
# It does not import login cookies, install software, or execute browser code.
# Run in Terminal: bash ~/Downloads/shelf-instagram.sh
# Optional: SHELF_OUT=/path/to/folder SHELF_PAUSE=2 bash shelf-instagram.sh
# Exit codes: 0 complete; 1 a download or file operation failed; 2 invalid links;
# 127 yt-dlp missing; 130 interrupted. Existing completed files are retained.
set -u
umask 077
out="\${SHELF_OUT:-$HOME/Movies/Shelf}"
pause="\${SHELF_PAUSE:-2}"
case "$pause" in 0|1|2|3|5) ;; *) pause=2 ;; esac
urls=(
%URLS%
)
re='^https://www\\.instagram\\.com/(p|reel|tv)/([A-Za-z0-9_-]{5,20})/$'
if [ "\${#urls[@]}" -eq 0 ] || [ "\${#urls[@]}" -gt 500 ]; then
  echo "Choose between 1 and 500 Instagram links." >&2; exit 2
fi
for url in "\${urls[@]}"; do
  [[ $url =~ $re ]] || { echo "Refusing unexpected link: $url" >&2; exit 2; }
done
bin="$(command -v yt-dlp || true)"
if [ -z "$bin" ]; then
  here="$(cd "$(dirname "$0")" && pwd)" || exit 1
  for candidate in "$here/yt-dlp_macos" "$HOME/Downloads/yt-dlp_macos" /opt/homebrew/bin/yt-dlp /usr/local/bin/yt-dlp; do
    if [ -f "$candidate" ] && [ -x "$candidate" ]; then bin="$candidate"; break; fi
  done
fi
if [ -z "$bin" ]; then
  echo "yt-dlp was not found. If you use Homebrew, run: brew install yt-dlp" >&2
  echo "Official setup: https://github.com/yt-dlp/yt-dlp/wiki/Installation" >&2
  exit 127
fi
mkdir -p -- "$out" || exit 1
lock="$out/.shelf-download-lock"
if ! mkdir -- "$lock" 2>/dev/null; then
  echo "Shelf cannot acquire its download lock: $lock" >&2
  echo "Check whether another Shelf script is running. After it stops, an abandoned lock may be removed." >&2
  exit 1
fi
logtmp=""
cleanup() {
  if [ -n "$logtmp" ] && [ -f "$logtmp" ]; then rm -f -- "$logtmp"; fi
  rmdir -- "$lock" 2>/dev/null || true
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
failed="$out/shelf-failed.txt"
if [ -e "$failed" ] && { [ ! -f "$failed" ] || [ ! -r "$failed" ]; }; then
  echo "Cannot read the existing failure log: $failed" >&2; exit 1
fi

has_media() {
  local media
  for media in "$1"/*.mp4 "$1"/*.mov "$1"/*.m4v "$1"/*.webm "$1"/*.mkv "$1"/*.MP4 "$1"/*.MOV "$1"/*.M4V "$1"/*.WEBM "$1"/*.MKV; do
    if [ -f "$media" ] && [ -s "$media" ]; then return 0; fi
  done
  return 1
}
has_info() {
  local info
  for info in "$1"/*.info.json; do
    if [ -f "$info" ] && [ -s "$info" ]; then return 0; fi
  done
  return 1
}
was_failed() {
  if [ -f "$failed" ]; then
    grep -E -q -- "^https://www[.]instagram[.]com/(p|reel|tv)/$1/$" "$failed"
  else return 1; fi
}
record_result() {
  # Replace only this post's result; unrelated prior failures survive every run.
  logtmp="$(mktemp "$out/.shelf-failed.XXXXXX")" || return 1
  if [ -f "$failed" ]; then
    awk -v target="$1" -v code="$code" '$0 != target && $0 !~ ("^https://www[.]instagram[.]com/(p|reel|tv)/" code "/$")' "$failed" > "$logtmp" || return 1
  fi
  if [ "$2" = failed ]; then printf '%s\\n' "$1" >> "$logtmp" || return 1; fi
  mv -f -- "$logtmp" "$failed" || return 1
  logtmp=""
}

ok=0; fail=0; skipped=0
for url in "\${urls[@]}"; do
  [[ $url =~ $re ]]; code="\${BASH_REMATCH[2]}"; dir="$out/$code"
  if has_media "$dir" && has_info "$dir" && ! was_failed "$code"; then
    record_result "$url" saved || { echo "Cannot update the failure log." >&2; exit 1; }
    echo "Already saved: $code"; ok=$((ok + 1)); skipped=$((skipped + 1)); continue
  fi
  printf '\\n-> %s\\n' "$url"
  status=1
  if mkdir -p -- "$dir"; then
    "$bin" --ignore-config --no-plugin-dirs --no-cookies --no-cookies-from-browser --no-playlist \\
      -f 'b[ext=mp4]/b/bv[ext=mp4]/bv' --fixup warn --write-info-json \\
      --no-overwrites --restrict-filenames --no-mtime --retries 3 --fragment-retries 3 \\
      --socket-timeout 30 --newline -P "$dir" -o '%(id)s.%(ext)s' -- "$url"
    status=$?
  fi
  if [ "$status" -eq 0 ] && has_media "$dir" && has_info "$dir"; then
    record_result "$url" saved || { echo "Cannot update the failure log." >&2; exit 1; }
    ok=$((ok + 1))
  else
    record_result "$url" failed || { echo "Cannot update the failure log." >&2; exit 1; }
    fail=$((fail + 1))
    if [ "$status" -eq 0 ]; then
      echo "The downloader returned success but no complete video and metadata pair was found." >&2
    else
      echo "Could not save this link. It may require a login, be unavailable, or have hit a network restriction." >&2
    fi
  fi
  sleep "$pause"
done
printf '\\nFinished: %s saved, %s failed (%s already present).\\n' "$ok" "$fail" "$skipped"
if [ -s "$failed" ]; then echo "Outstanding failed links: $failed" >&2; fi
echo "Next: return to the Shelf webpage, choose Open saved folder, and select: $out"
if [ "$fail" -gt 0 ]; then exit 1; fi
exit 0
`;
  const api = { template };
  if (typeof module !== 'undefined' && module.exports) module.exports = api; else root.ShelfScript = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
